# Generated by Django 3.2 on 2023-05-12 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('fac', models.CharField(choices=[('Agricultural Science', 'Agricultural Science'), ('Arts', 'Arts'), ('Biological Science', 'Biological Science'), ('Management Science', 'Management Science'), ('Densitry', 'Densitry'), ('Education', 'Education'), ('Engineering', 'Engineering'), ('Health Science and Technology', 'Health Science and Technology'), ('Law', 'Law'), ('Medical Science', 'Medical Science'), ('Pharmaceutical Science', 'Pharmaceutical Science'), ('Physical Science', 'Physical Science'), ('Veterinary Medicine', 'Veterinary Medicine'), ('', 'Choose A Faculty')], default='', max_length=100, unique=True)),
                ('job', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('dept', models.CharField(blank=True, max_length=100, null=True)),
                ('img', models.ImageField(blank=True, help_text='Upload your image ', null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': ' Team Members',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True, null=True)),
                ('f_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.department', to_field='fac')),
            ],
            options={
                'verbose_name_plural': 'Faculties',
            },
        ),
    ]
