# Generated by Django 3.2 on 2023-05-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20230511_1757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': 'Departments'},
        ),
        migrations.AddField(
            model_name='department',
            name='job',
            field=models.TextField(blank=True, null=True),
        ),
    ]
