# Generated by Django 3.2 on 2023-05-12 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_faculty_f_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='f_name',
        ),
    ]
