# Generated by Django 3.2 on 2023-05-12 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_faculty_f_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='f_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.department'),
        ),
    ]
