# Generated by Django 3.2 on 2023-05-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_department_fac'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
