# Generated by Django 3.2 on 2023-05-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_auto_20230513_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='f_slug',
            field=models.SlugField(blank=True, max_length=200, null=True, verbose_name='faculty slug'),
        ),
    ]
